markdown: rdiscount
permalink: /:title/
encoding: utf-8
url: http://www.iamyuchao.com
name: I am Yu Chao
author: Lucas Yu
qq: 87792280
weibo: 1714379531
github: windea
duoshuo: windea
pygments: true
safe: true
paginate: 20
about: ""
description: 
